Proposal for a convention for a new importer function
adobe/helix-importer-ui pull request #102
Opened 2023-01-31 10:53 UTC by catalan-adobe

Proposal for a convention for a new importer function to execute javascript after page load.

This could be used to wait for specific DOM element to be present before execution the transform function

## bacom example

https://business.adobe.com/au/resources/reports/3partstrategyforuppingyourgame.html

The page loads an external form which can take few seconds to be added to the DOM.
Rather than adding a fixed waiting time which would greatly affect bulk imports, this proposal would allow following mechanism in import.js:

1. At the top of import.js, add util function to wait for a DOM element to exist
```
[...]
async function awaitElement(selector, main, timeout = 10000) {
  return new Promise((resolve, reject) => {
    const timeWas = new Date();
    const wait = setInterval(function() {

      console.log('poll check', main.querySelector(selector));
      if (main.querySelector(selector)) {
        console.log("resolved after", new Date() - timeWas, "ms");
        clearInterval(wait);
        resolve();
      } else if (new Date() - timeWas > timeout) { // Timeout
        console.log("rejected after", new Date() - timeWas, "ms");
        clearInterval(wait);
        reject();
      }
    }, 200);
  });
}
[...]
```

2. In `export default {`, add following "convention" function `postLoadScript`
```
[...]
export default {
  postLoadScript: (async (document) => {
    try {
      await awaitElement('.faas-form-settings', main, 2500);
      await awaitElement('.faas-form', main, 2500);
    } catch (e) {
      console.error('no form found!', url);
    }
  }),
[...]
transformDOM: ({
[...]
```

2023-02-01 13:12 UTC, kptdobe commented
Also, I feel like this wait operation is the feature want to have, not a generic entry point into something as a user I would know what to do with.

2023-02-08 10:08 UTC, kptdobe commented on js/import/import.ui.js
> +                    if (config.importer.projectTransform.onLoad) {
```suggestion
                    if (config.importer.projectTransform?.onLoad) {
```

2023-02-08 10:11 UTC, kptdobe requested changes

2023-02-08 10:11 UTC, kptdobe commented on js/import/import.ui.js
> +                      await config.importer.projectTransform.onLoad(frame.contentDocument);
```suggestion
                      await config.importer.projectTransform.onLoad({ 
                          document: frame.contentDocument,
                          url: replacedURL,
                          params: { originalURL },                          
                      });
```

2023-02-08 10:11 UTC, kptdobe commented on js/import/import.ui.js
> +                      await config.importer.projectTransform.onLoad(frame.contentDocument);
To get the similar set of parameters than other methods.

2023-02-08 13:42 UTC, catalan-adobe commented on js/import/import.ui.js
> +                      await config.importer.projectTransform.onLoad(frame.contentDocument);
fixed in https://github.com/adobe/helix-importer-ui/pull/102/commits/43d9244e81b32ecd8d1046befe07860336136ba1

2023-02-08 13:44 UTC, catalan-adobe commented
@kptdobe, ready for another round of review :) Feedback should be adressed:
* [d061bcc](https://github.com/adobe/helix-importer-ui/pull/102/commits/d061bcc127ef027c93f8cbbf9f194620ffe51e29) merged main, no more conflicts
* [a1dab3d](https://github.com/adobe/helix-importer-ui/pull/102/commits/a1dab3d4c9a3a07d9590e5057e3805500f65127c) updated helix-importer dependency and executed `npm run build:prod`
* [43d9244](https://github.com/adobe/helix-importer-ui/pull/102/commits/43d9244e81b32ecd8d1046befe07860336136ba1) refactored `onLoad` based on latest feedback

2023-02-08 15:21 UTC, kptdobe requested changes
Please also remove [js/dist/helix-importer.js](https://github.com/adobe/helix-importer-ui/pull/102/files#diff-9b9a5e97d6d559d3f229bc2114e0da7fbc4de94d1a68dcf0351b3b2aaac46046) from PR

2023-02-08 15:21 UTC, kptdobe commented on js/shared/pollimporter.js
> +  #onLoad = async () => {};
useless no ?

2023-02-08 19:21 UTC, catalan-adobe commented on js/shared/pollimporter.js
> +  #onLoad = async () => {};
indeed!

2023-02-08 19:22 UTC, catalan-adobe commented on package.json
> +    "@adobe/helix-importer": "2.8.0",
done.

2023-02-09 08:03 UTC, kptdobe approved these changes

2023-02-09 08:03 UTC, kptdobe commented on js/shared/pollimporter.js
> +        return true;
```suggestion
```
This `return true` is useless.

2023-02-09 08:21 UTC, catalan-adobe commented on js/shared/pollimporter.js
> +        return true;
Good catch!

2023-02-09 10:12 UTC, merged