[Manual Mapping] Maintain the mapping for more than 1 URL in the localstorage.
adobe/helix-importer-ui pull request #354
Opened 2024-05-15 16:21 UTC by atopper

## Description
The mapping for 1 URL is deleted if the URL is changed, and a new mapping is started.  Work can be lost easily this way.  This change maintains multiple URls in the local storage

## Related Issue

## Motivation and Context

Ensure mappings are saved.

## How Has This Been Tested?

Manually and ran tests.

## Screenshots (if appropriate):
![image](https://github.com/adobe/helix-importer-ui/assets/7156029/b7e0c5ac-f700-4f82-a8de-7b25cfe8d6ff)

## Types of changes
I'll say bug, although 'new feature' might apply.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2024-05-16 11:10 UTC, catalan-adobe reviewed
Thanks for the contribution! Overall LGTM. Few cosmetic comments below :)

2024-05-16 11:10 UTC, catalan-adobe commented on js/dist/helix-importer.js
> -
`js/dist/*` files should not be modified directly. They are external dependencies built by the project.

2024-05-16 11:10 UTC, catalan-adobe commented on js/sections-mapping/sections-mapping.import.js
>  }
Let's use `getImporterSectionMapping` directly and get rid of `getSectionsMappingData`

2024-05-16 11:10 UTC, catalan-adobe commented on js/sections-mapping/sections-mapping.import.js
> +
Let's remove this empty line.

2024-05-16 14:42 UTC, atopper commented
Do you think instead of the URL as the 'key', to use the hostname instead, so that any subpages are saved in the same mapping?
Probably not needed for the pre-sales demo, but it is something that I keep wondering about.

2024-05-16 14:54 UTC, atopper commented on .gitignore
> +# js/dist/* (maybe?)
@catalan-adobe  Is this a good idea (commented for now)? ☝️

2024-05-16 15:00 UTC, atopper commented on js/dist/helix-importer.js
> -
My Intellij keeps formatting it for me 🙄.  I'll get there.  Going to command line now.

2024-05-22 05:00 UTC, catalan-adobe commented on .gitignore
> +# js/dist/* (maybe?)
No. We might debate on the naming but historically this folder contain dependency "vendor" files we need in the project.

2024-05-22 05:03 UTC, catalan-adobe commented on js/shared/mappings.js
Neatpicking but everything about sections mapping is very specific so for now I would prefer to see this under `/js/sections-mapping/utils.js` (or `utils.ui.js`).

2024-05-22 05:04 UTC, catalan-adobe requested changes
Thanks for the changes! I would just like `/js/shared/mapping.js` to be moved to `/js/sections-mapping/utils.js` (or `utils.ui.js`)

2024-05-22 15:09 UTC, atopper commented on js/shared/mappings.js
Being picky is appreciated!

2024-07-09 15:22 UTC, closed without merging