feat: Express Import ruleset JSON
adobe/helix-importer-ui pull request #378
Opened 2024-06-14 20:05 UTC by arumsey

## Description

- add support for import rules JSON
- convert section mapping to import rules
- download import rules
- toggle usage of import rules vs section mapping
 
## Related Issue

#355 

## Motivation and Context

## Screenshots (if appropriate):
<img width="1743" alt="image" src="https://github.com/adobe/helix-importer-ui/assets/1004204/5ec52957-6f7f-421a-b34d-73e5aa999ebc">

## Types of changes

- extending AEM Importer to more non-technical users
- decreasing the time required to perform an import

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2024-06-14 20:27 UTC, arumsey commented on import-express.html
> -                            <sp-tab label="HTML" value="import-html"></sp-tab>
Removing complexity from Express mode. Go to Workbench mode when you want to dig deeper.

2024-06-17 07:36 UTC, catalan-adobe commented on import-express.html
> -                            <sp-tab label="HTML" value="import-html"></sp-tab>
These tabs still have values when doing manual section mapping. I would prefer to keep them.

2024-06-17 07:38 UTC, catalan-adobe commented on import-express.html
> +                                        <sp-textfield class="option-field" data-locked="true" id="import-file-url" type="url" value="http://localhost:3001/tools/importer/helix-importer-ui/js/sections
```suggestion
                                        <sp-textfield class="option-field" data-locked="true" id="import-file-url" type="url" value="http://localhost:3001/tools/importer/helix-importer-ui/js/sections-mapping/import/sections-mapping.import.js" disabled></sp-textfield>
```

2024-06-17 07:42 UTC, catalan-adobe commented on js/import/import.ui.js
> +        files.push({ type: 'html', filename: `${path}.html`, data: `<html lang="en"><head><title>Import</title></title></head>${html}</html>` });
Why enforcing a title here? Also, there is a duplicate of `</title>`.

2024-06-17 07:45 UTC, catalan-adobe commented on js/sections-mapping/sm.ui.js
> +      { label: 'Exclude', attributes: { value: 'exclude' } },
This is confusing at first sight when doing manual section mapping. Unmapped content is excluded by default. Also there is no notion of `Root`.
Would it be possible to move these options in a dedicated section?

2024-06-17 07:56 UTC, catalan-adobe requested changes
@arumsey, overall LGTM. I commented some minor points.
I see many changes in the `js/dist/` folder, can you detail why they happened?

2024-06-17 12:50 UTC, atopper commented on js/import/import.ui.js
> +    const mapping = getSectionsMappingData(originalURL) || [];
This part may be dependent on https://github.com/adobe/helix-importer-ui/pull/354 (mappings saved per URL).

2024-06-17 12:52 UTC, atopper commented on js/import/import.ui.js
> +        files.push({ type: 'html', filename: `${path}.html`, data: `<html lang="en"><head><title>Import</title></title></head>${html}</html>` });
I was getting style errors that `title` was required on HTML so I thought I'd satisfy its urgency.  Not necessary (definitely not the duplicate).

2024-06-17 12:56 UTC, atopper commented on js/sections-mapping/sm.ui.js
> +      { label: 'Exclude', attributes: { value: 'exclude' } },
This may need discussion.  I think this approach assumes non-mapped elements will fall to 'default rendering' so that any addition import.js code will run on it.
`Root` might be good discussion too (as it could make picking selectors or XPaths tricky).

2024-06-17 14:51 UTC, arumsey commented on import-express.html
> -                            <sp-tab label="HTML" value="import-html"></sp-tab>
Would these tabs only provide value to a developer doing section mapping? If the expected user of express importing (section mapping) is a non-techical user would there be any value to them being able to view MD and HTML? For now I am happy to keep these tabs but as this feature progresses I think getting a full XD review on what is absolutely neccessary within an Express view wold be useful. Especially, since all of these features would still be available in the more advanced Workbench mode.

2024-06-17 15:02 UTC, arumsey commented on js/sections-mapping/sm.ui.js
> +      { label: 'Exclude', attributes: { value: 'exclude' } },
This would be the main departure between section mapping and import rules. Import rules attempts to mimic the existing import script process where there is not need to identify default content. All the import rules need to identify is what content you want to eclude and what content should be transformed into blocks. The concept of a root element was also brought forward from import scripts as a way to automatically ignore anything outside of this root element. Since the import rules should always be machine gnerated however we could force the root element to always be `body` in order to reduce complexity of the import rules.

2024-06-17 15:03 UTC, arumsey commented on js/sections-mapping/sm.ui.js
> +      { label: 'Exclude', attributes: { value: 'exclude' } },
@atopper In the short term, `root` can be removed and we can move `Exclude` to its own section at the bottom until we can discuss the merits of exluding exerything by default vs. including exerything by default.

2024-06-17 15:05 UTC, arumsey commented on import-express.html
> -                            <sp-tab label="HTML" value="import-html"></sp-tab>
@atopper Lets add these tabs back for now.

2024-06-17 15:10 UTC, arumsey commented
> @arumsey, overall LGTM. I commented some minor points. I see many changes in the `js/dist/` folder, can you detail why they happened?

@catalan-adobe The import rules feature has been added as an addition to the `helix-importer` module which requires a rebuild (`npm run build`). This decision was made so that import rules could potnetially be moved to `helix-importer` for easier consumption by the importer service in Spacecat.

2024-06-17 17:40 UTC, atopper approved these changes

2024-06-17 23:33 UTC, arumsey commented
Thanks for committing the requested changes @atopper. These look good to me as a first pass at integrating import rules with section mapping.

2024-06-18 17:17 UTC, atopper commented
@catalan-adobe  There's a good chance that Anthony and I do not have permission to merge this.  Could you do it?  We can discuss merge requirements & permissions next week or beyond.

2024-06-19 15:20 UTC, merged